name: Deploy Frontend (Next.js) to Rocky

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # (ทางเลือก) ล้างของเก่าที่เซิร์ฟเวอร์ ยกเว้น env/pm2
      - name: Clean old build (keep env & pm2 config)
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /var/www/fuse-nextjs
            find . -mindepth 1 -maxdepth 1 \
              ! -name 'ecosystem.frontend.js' \
              ! -name '.env.production' \
              -exec rm -rf {} +

      - name: Upload source to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: |
            .
            !.git/
            !node_modules/
            !.next/
          target: /var/www/fuse-nextjs

      - name: Build & reload on server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install --lts
            nvm use --lts >/dev/null

            cd /var/www/fuse-nextjs
            if [ -f package-lock.json ]; then
              npm ci --no-audit --no-fund
            else
              npm i --no-audit --no-fund
            fi

            npm run build
            pm2 startOrReload ecosystem.frontend.js --update-env || pm2 start /var/www/fuse-nextjs/ecosystem.frontend.js
            pm2 save
